# Generated by Django 5.1.1 on 2025-02-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_purchaseexpense_paid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, default='Pcs', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseexpense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchaseexpense',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseexpense',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseexpense',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='purchaseexpense',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='purchaseexpense',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='purchaseexpense',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='expenses', to='inventory.purchaseproduct'),
        ),
    ]
