# Generated by Django 5.1.1 on 2025-02-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_purchaseexpense_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproduct',
            name='product',
            field=models.CharField(blank=True, default='Product', max_length=255, null=True),
        ),
    ]
