# Generated by Django 5.1.1 on 2025-02-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_purchaseexpense_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseexpense',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
